# config.yaml 예시
train_root: './upscaled/train'
test_root: './upscaled/test'
pretrained_weights: 
sample_submission: 'open/sample_submission.csv'
backbone: 'vit'
img_size: 280
crop_size: 224
train_batch_size: 4
val_batch_size: 4
train_num_workers: 8
val_num_workers: 8
num_workers: 6  # (개별 값이 없을 때 fallback)
batch_size: 6 # (개별 값이 없을 때 fallback)
epochs: 20 
seed: 42
num_classes: -1
wandb:
  entity: 'Dacon_Car'
  project: 'car-classification'
  name: 'vit'
use_swa: false
auto_scale_batch_size: true
gradient_clip_val: 1.0

# Early stopping
early_stopping_monitor: val_logloss
early_stopping_patience: 6
early_stopping_mode: min
early_stopping_min_delta: 0.0

# Checkpoint
checkpoint_dir: C:/Users/bug95/DaconHectoAIChallenge
checkpoint_monitor: val_logloss
checkpoint_save_top_k: 1
checkpoint_mode: min
checkpoint_filename: best_model

accumulate_grad_batches : 4
learning_rate: 1e-5
eta_min: 5e-7
optimizer: adamw
scheduler: linear_warmup_cosine  # step, cosine, reduce_on_plateau 중 선택
weight_decay: 0.01
label_smoothing: 0.015
step_size: 5   # StepLR용 (15에폭 내 2~3회 감소)
gamma: 0.2      # StepLR용
# ReduceLROnPlateau용 옵션
plateau_patience: 2
plateau_factor: 0.2
plateau_min_lr: 1e-7
plateau_mode: min
plateau_monitor: val_logloss

checkpoint_path: best_model-v11.ckpt

# Img mix Augmentation
Img_Mix: False
mixmethod: snapmix
prob: 0.5
beta: 5