# config.yaml 예시
train_root: '/content/drive/MyDrive/Obsidian/Dacon/Hecto_AI_Challenge/upscaled/train'
test_root: '/content/drive/MyDrive/Obsidian/Dacon/Hecto_AI_Challenge/upscaled/test'
pretrained_weights: '/content/drive/MyDrive/Obsidian/Dacon/Hecto_AI_Challenge/Pretrained/Stanford_Cars_TResNet-L_Student_Weight.pth'
sample_submission: 'open/sample_submission.csv'
backbone: 'tresnet_student'
img_size: 421
crop_size: 368
train_batch_size: 96
val_batch_size: 32
train_num_workers: 12
val_num_workers: 12
num_workers: 12  # (개별 값이 없을 때 fallback)
batch_size: 64  # (개별 값이 없을 때 fallback)
epochs: 30
learning_rate: 0.002
seed: 42
num_classes: -1
wandb:
  entity: 'Dacon_Car'
  project: 'car-classification'
  name: 'TResNet_student_affine_perspective'
use_swa: false
swa_lr: 0.002
use_ema: false
ema_decay: 0.999
auto_scale_batch_size: true
gradient_clip_val: 1.0

early_stopping_monitor: val_loss
early_stopping_patience: 3
early_stopping_mode: min
early_stopping_min_delta: 0.0

checkpoint_dir: C:/Users/bug95/DaconHectoAIChallenge
checkpoint_monitor: val_loss
checkpoint_save_top_k: 1
checkpoint_mode: min
checkpoint_filename: best_model