# config.yaml 예시
train_root: './upscaled/train'
test_root: './upscaled/test'
pretrained_weights: 
sample_submission: 'open/sample_submission.csv'
backbone: 'effnet_m'
img_size: 480
crop_size: 384
train_batch_size: 24
val_batch_size: 24
train_num_workers: 12
val_num_workers: 12
num_workers: 6  # (개별 값이 없을 때 fallback)
batch_size: 6 # (개별 값이 없을 때 fallback)
epochs: 30 
seed: 42
num_classes: -1
wandb:
  entity: 'Dacon_Car'
  project: 'car-classification'
  name: 'effnet_m'
use_swa: false
auto_scale_batch_size: true
gradient_clip_val: 1.0

# Early stopping
early_stopping_monitor: val_logloss
early_stopping_patience: 4
early_stopping_mode: min
early_stopping_min_delta: 0.0

# Checkpoint
checkpoint_dir: C:/Users/bug95/DaconHectoAIChallenge
checkpoint_monitor: val_logloss
checkpoint_save_top_k: 1
checkpoint_mode: min
checkpoint_filename: best_model

accumulate_grad_batches : 2
learning_rate: 5e-5
optimizer: adamw
scheduler: reduce_on_plateau  # step, cosine, reduce_on_plateau 중 선택
weight_decay: 0.01
label_smoothing: 0.02
step_size: 5   # StepLR용 (15에폭 내 2~3회 감소)
gamma: 0.2      # StepLR용
# ReduceLROnPlateau용 옵션
plateau_patience: 2
plateau_factor: 0.2
plateau_min_lr: 1e-7
plateau_mode: min
plateau_monitor: val_logloss

checkpoint_path:

# Img mix Augmentation
Img_Mix: True
mixmethod: snapmix
prob: 0.5
beta: 5