seed: 42
batch_size: 56
num_workers: 12
img_size: 280
crop_size: 224
train_root: upscaled/train
test_root: upscaled/test
sample_submission: open/sample_submission.csv
checkpoint_path: swin_base.ckpt
backbone: 'swin_base'
tta:
  multiscale: [224]
  flip: true